version: '3'
services:
  api:
    tty: true
    stdin_open: true
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/code:rw
    depends_on:
      - mongo
    entrypoint:
      - sh
    ports:
      - '5000:5000'

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db